#version: '3.9.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    volumes:
      - ./nginx/minerva.conf:/etc/nginx/nginx.conf
      - ./src/static:/src/static
      - ./src/media:/src/media
    depends_on:
      - web
    networks:
      - nginx_network
  web:
    build: src
    command: gunicorn minerva.wsgi -b 0.0.0.0:8000
    volumes:
      - ./src/:/src/
      - static_volume:/src/static
      - media_volume:/src/media
    ports:
      - 8000
    networks:
      - nginx_network
  ui:
    build: ./ui
    command: npm start
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - web
  db:
    image: postgres:14.1-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbadmin
      - POSTGRES_PASSWORD=dbadmin
      - POSTGRES_DB=minerva
volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  nginx_network:
    driver: bridge